### ISSUE TITLE
Error title

### ISSUE THREAD

**Issue by aapeliv** [persephone-tools/persephone-web-API#144]
What do you think about an error title to be added to the error spec?

This could be used in the frontend, there'll be a little error box, but it'd be nicer to have the title something else than "Uh-oh an error occured"

**Comment by shuttle1987** [comment]
If it makes the frontend better I would be open to it. That said I think error codes are the better way to go here because you can create a lookup table with the error code number and the title text. This is easier for internationalization in the case that we do it. It also allows the frontend to change the display without needing upstream support provided the errors are the same.
