### ISSUE TITLE
Support ".wave" extension?

### ISSUE THREAD

**Issue by shuttle1987** [persephone-tools/persephone-web-API#18]
Should we support this?

**Comment by shuttle1987** [comment]
@alexis-michaud  Thanks for the feedback here!

> This is the first I hear of a .wave extension. It would be a doublet for .wav, like the .html doublet for .htm, right?

Yes it is exactly like this, I very rarely see files with the `.wave` extension however.
I suspect the way to handle this is to have an API endpoint that expects files in WAV format only and will then store those files with the appropriate extension. Generally speaking I would like to avoid API endpoints that will change their behavior based on what the file contains, this is something that the Application code that will use the API is free to determine however.

In the case of MP3 or other less desirable encodings this may be handled via another API endpoint but for now the priority has to be to get the `.wav` files supported first.

**Comment by oadams** [comment]
It seems there are two ends of a spectrum. Rejecting ".wave" extensions is at one end (overly strict), and inferring the filetype from content and disregarding the extension is at the other end (too lax, encouraging sloppiness).

Though uncommon, ".wave" is an extension that gets used for WAV files and it should be supported. Inferring the filetype from content is just getting overly tricksy because we might not be able to generalize that behaviour to other file types where that inference is not possible, making expected behaviour of persephone more difficult to ascertain. Users should just call  their WAVs ".wave" or ".wav".

**Comment by shuttle1987** [comment]
So my general approach is to allow a WAV file if it has the right extension and to make the upload fail if the contents of the WAV do not match what what is required in a WAV file. I feel as though guessing filetypes should be the responsibility of the front end, not the API.

Persephone is hardcoded to take in `.wav` extensions right now, but that's not an issue because Persephone won't run anything on original filenames due to security reasons.

**Comment by shuttle1987** [comment]
Currently this will just rename `.wave` to `.wav` internally.
